import pyautogui

pyautogui.press('win')
pyautogui.sleep(1)
pyautogui.write('chrome')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.write('https://mail.google.com/mail/u/0/#inbox')
pyautogui.press('enter')
pyautogui.sleep(2)
pyautogui.click(40 ,230)
pyautogui.sleep(2)
pyautogui.write('rafaelsilvap0004@gmail.com')
pyautogui.sleep(2)
pyautogui.click(1275, 532)
pyautogui.write('bilauuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu')
pyautogui.sleep(2)
pyautogui.click(1292, 1004)