import pyautogui

pyautogui.press('win')
pyautogui.sleep(1)
pyautogui.write('chrome')
pyautogui.sleep(1)
pyautogui.click(  846 ,511)
pyautogui.sleep(1)
pyautogui.write('https://openai.com/')
pyautogui.press('enter')
pyautogui.sleep(2)
pyautogui.click(909, 501)
pyautogui.sleep(2)
pyautogui.write('ola chat')
pyautogui.press('enter')
pyautogui.sleep(2)
pyautogui.click(787 ,929)
pyautogui.write('estou fazendo testes com o pyautogui mas nao sei o que fazer, poderIA me dar algumas ideias')
pyautogui.sleep(2)
pyautogui.press('enter')